[servers]
[servers.production]
server01 ansible_host=10.0.1.10 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
server02 ansible_host=10.0.1.11 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[kubernetes_masters]
master01 ansible_host=10.0.2.10 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[kubernetes_workers]
worker01 ansible_host=10.0.2.11 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
worker02 ansible_host=10.0.2.12 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[monitoring]
monitor01 ansible_host=10.0.3.10 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[all:vars]
ansible_python_interpreter=/usr/bin/python3
app_name=digitallist
docker_registry=registry.digitallist.app
k8s_namespace=digitallist
